/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import "./Documents.css";
import Layout from "../../components/Layout/Layout";
import { ErrorNotice, LoadingState, Modal, PageHeader, StatusBadge, formatDate } from "../../components/AdminUI/AdminUI";
import DocumentsService from "../../services/documentsService";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import DownloadRoundedIcon from "@mui/icons-material/DownloadRounded";

const errorText = (error) => error.response?.data?.detail || "Une erreur est survenue. Veuillez réessayer.";
const documentId = (document) => document._id || document.id;
const typeLabel = (type) => type === "audio" ? "Audio" : "Document";

function EditDocument({ document, onClose, onSaved }) {
  const [title, setTitle] = useState(document.title || ""); const [summary, setSummary] = useState(document.ai_metadata?.summary || ""); const [keywords, setKeywords] = useState((document.ai_metadata?.keywords || []).join(", ")); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(""); await DocumentsService.update(documentId(document), { title, summary, keywords: keywords.split(",").map((item) => item.trim()).filter(Boolean) }); onSaved(); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } };
  return <Modal title="Modifier le document" onClose={onClose}><form onSubmit={submit}><div className="form-grid"><ErrorNotice message={error} /><div className="form-field full"><label>Titre</label><input className="input-control" value={title} onChange={(event) => setTitle(event.target.value)} required /></div><div className="form-field full"><label>Résumé</label><textarea className="input-control textarea-control" value={summary} onChange={(event) => setSummary(event.target.value)} rows="4" /></div><div className="form-field full"><label>Mots-clés <small>(séparés par une virgule)</small></label><input className="input-control" value={keywords} onChange={(event) => setKeywords(event.target.value)} /></div></div><div className="modal-footer"><button type="button" className="button button-secondary" onClick={onClose}>Annuler</button><button className="button button-primary" disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div></form></Modal>;
}

function DocumentDetails({ document, onClose }) { return <Modal title="Détails du document" onClose={onClose}><div className="details-grid"><div><span>Titre</span><strong>{document.title}</strong></div><div><span>Fichier source</span><strong>{document.original_filename || "—"}</strong></div><div><span>Type</span><strong>{typeLabel(document.file_type)}</strong></div><div><span>Statut</span><StatusBadge value={document.status} /></div><div><span>Date d’ajout</span><strong>{formatDate(document.created_at)}</strong></div><div><span>Taille</span><strong>{document.file_size ? `${(document.file_size / 1024 / 1024).toFixed(2)} Mo` : "—"}</strong></div></div><div className="modal-footer"><button className="button button-secondary" type="button" onClick={onClose}>Fermer</button></div></Modal>; }

function Documents() {
  const [documents, setDocuments] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [status, setStatus] = useState(""), [page, setPage] = useState(1), [modal, setModal] = useState(null); const perPage = 8;
  const load = async () => { try { setLoading(true); setError(""); setDocuments(await DocumentsService.getAll()); } catch (err) { setError(errorText(err)); } finally { setLoading(false); } }; useEffect(() => { load(); }, []);
  const filtered = useMemo(() => documents.filter((document) => (`${document.title} ${document.original_filename} ${document.file_type}`).toLowerCase().includes(query.toLowerCase()) && (!status || document.status === status)), [documents, query, status]); const pages = Math.max(1, Math.ceil(filtered.length / perPage)); const visible = filtered.slice((page - 1) * perPage, page * perPage); useEffect(() => { setPage(1); }, [query, status]);
  const remove = async (document) => { if (!window.confirm(`Supprimer définitivement « ${document.title} » ?`)) return; try { await DocumentsService.remove(documentId(document)); await load(); } catch (err) { setError(errorText(err)); } }; const saved = async () => { setModal(null); await load(); };
  return <Layout><main className="admin-page"><PageHeader title="Documents" description="Consultez et administrez les documents archivés." /><ErrorNotice message={error} /><section className="panel"><div className="toolbar"><div className="toolbar-left"><label className="search-control"><SearchRoundedIcon /><input className="input-control" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un document" /></label><select className="select-control" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tous les statuts</option><option value="UPLOADED">Importé</option><option value="PROCESSING">En traitement</option><option value="COMPLETED">Terminé</option><option value="FAILED">Échec</option></select></div><span className="table-count">{filtered.length} document{filtered.length !== 1 ? "s" : ""}</span></div>{loading ? <LoadingState /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Titre</th><th>Type</th><th>Date d’ajout</th><th>Statut</th><th aria-label="Actions" /></tr></thead><tbody>{visible.length ? visible.map((document) => <tr key={documentId(document)}><td><div className="strong">{document.title}</div><small>{document.original_filename}</small></td><td>{typeLabel(document.file_type)}</td><td>{formatDate(document.created_at)}</td><td><StatusBadge value={document.status} /></td><td><div className="actions"><button className="icon-button" title="Voir les détails" onClick={() => setModal({ type: "view", document })}><VisibilityOutlinedIcon /></button><button className="icon-button" title="Modifier" onClick={() => setModal({ type: "edit", document })}><EditOutlinedIcon /></button><a className="icon-button" title="Télécharger" href={`http://localhost:8000/documents/${documentId(document)}/download`}><DownloadRoundedIcon /></a><button className="icon-button danger" title="Supprimer" onClick={() => remove(document)}><DeleteOutlineRoundedIcon /></button></div></td></tr>) : <tr><td colSpan="5"><div className="empty-state">Aucun document.</div></td></tr>}</tbody></table></div>}<div className="pagination"><span>Page {page} sur {pages}</span><div className="pagination-controls"><button disabled={page === 1} onClick={() => setPage(page - 1)}>‹</button><button disabled={page === pages} onClick={() => setPage(page + 1)}>›</button></div></div></section>{modal?.type === "edit" && <EditDocument document={modal.document} onClose={() => setModal(null)} onSaved={saved} />}{modal?.type === "view" && <DocumentDetails document={modal.document} onClose={() => setModal(null)} />}</main></Layout>;
}
export default Documents;
