/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import "./Users.css";
import Layout from "../../components/Layout/Layout";
import { ErrorNotice, LoadingState, Modal, PageHeader, StatusBadge, roleLabel } from "../../components/AdminUI/AdminUI";
import UsersService from "../../services/usersService";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";

const blankUser = { first_name: "", last_name: "", email: "", phone: "", department: "", role: "SNRT_USER", status: "ACTIVE" };
const errorText = (error) => error.response?.data?.detail || "Une erreur est survenue. Veuillez réessayer.";

function UserForm({ user, onClose, onSaved }) {
  const [form, setForm] = useState(user || blankUser); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(""); if (user) await UsersService.update(user.user_id, form); else await UsersService.create(form); onSaved(); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } };
  return <Modal title={user ? "Modifier l’utilisateur" : "Ajouter un utilisateur"} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><ErrorNotice message={error} /><div className="form-field"><label>Prénom</label><input className="input-control" name="first_name" value={form.first_name} onChange={update} required /></div><div className="form-field"><label>Nom</label><input className="input-control" name="last_name" value={form.last_name} onChange={update} required /></div><div className="form-field full"><label>Email professionnel</label><input className="input-control" name="email" type="email" value={form.email} onChange={update} required /></div><div className="form-field"><label>Téléphone</label><input className="input-control" name="phone" value={form.phone} onChange={update} required /></div><div className="form-field"><label>Département</label><input className="input-control" name="department" value={form.department} onChange={update} required /></div><div className="form-field"><label>Rôle</label><select className="select-control" name="role" value={form.role} onChange={update}><option value="ADMIN">Administrateur</option><option value="DOCUMENTALIST">Documentaliste</option><option value="SNRT_USER">Utilisateur</option></select></div>{user && <div className="form-field"><label>Statut</label><select className="select-control" name="status" value={form.status} onChange={update}><option value="ACTIVE">Actif</option><option value="INACTIVE">Inactif</option></select></div>}</div><div className="modal-footer"><button className="button button-secondary" type="button" onClick={onClose}>Annuler</button><button className="button button-primary" disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div></form></Modal>;
}

function UserDetails({ user, onClose }) { return <Modal title="Détails de l’utilisateur" onClose={onClose}><div className="details-grid"><div><span>Prénom</span><strong>{user.first_name}</strong></div><div><span>Nom</span><strong>{user.last_name}</strong></div><div><span>Email</span><strong>{user.email}</strong></div><div><span>Téléphone</span><strong>{user.phone}</strong></div><div><span>Département</span><strong>{user.department}</strong></div><div><span>Rôle</span><strong>{roleLabel(user.role)}</strong></div><div><span>Statut</span><StatusBadge value={user.status} /></div><div><span>Identifiant</span><strong>{user.user_id}</strong></div></div><div className="modal-footer"><button className="button button-secondary" type="button" onClick={onClose}>Fermer</button></div></Modal>; }

function Users() {
  const [users, setUsers] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [role, setRole] = useState(""), [page, setPage] = useState(1), [modal, setModal] = useState(null); const perPage = 7;
  const load = async () => { try { setLoading(true); setError(""); setUsers(await UsersService.getAll()); } catch (err) { setError(errorText(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => users.filter((user) => (`${user.first_name} ${user.last_name} ${user.email} ${user.department}`).toLowerCase().includes(query.toLowerCase()) && (!role || user.role === role)), [users, query, role]);
  const pages = Math.max(1, Math.ceil(filtered.length / perPage)); const visible = filtered.slice((page - 1) * perPage, page * perPage);
  useEffect(() => { setPage(1); }, [query, role]);
  const remove = async (user) => { if (!window.confirm(`Supprimer définitivement ${user.first_name} ${user.last_name} ?`)) return; try { await UsersService.remove(user.user_id); await load(); } catch (err) { setError(errorText(err)); } };
  const saved = async () => { setModal(null); await load(); };
  return <Layout><main className="admin-page"><PageHeader title="Utilisateurs" description="Gérez les comptes et les accès à la plateforme." action={<button className="button button-primary" onClick={() => setModal({ type: "create" })}><AddRoundedIcon />Ajouter un utilisateur</button>} /><ErrorNotice message={error} /><section className="panel"><div className="toolbar"><div className="toolbar-left"><label className="search-control"><SearchRoundedIcon /><input className="input-control" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un utilisateur" /></label><select className="select-control" value={role} onChange={(event) => setRole(event.target.value)}><option value="">Tous les rôles</option><option value="ADMIN">Administrateurs</option><option value="DOCUMENTALIST">Documentalistes</option><option value="SNRT_USER">Utilisateurs</option></select></div><div className="toolbar-right"><span className="table-count">{filtered.length} utilisateur{filtered.length !== 1 ? "s" : ""}</span></div></div>{loading ? <LoadingState /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Utilisateur</th><th>Département</th><th>Rôle</th><th>Statut</th><th aria-label="Actions" /></tr></thead><tbody>{visible.length ? visible.map((user) => <tr key={user.user_id}><td><div className="strong">{user.first_name} {user.last_name}</div><small>{user.email}</small></td><td>{user.department}</td><td>{roleLabel(user.role)}</td><td><StatusBadge value={user.status} /></td><td><div className="actions"><button className="icon-button" title="Voir les détails" onClick={() => setModal({ type: "view", user })}><VisibilityOutlinedIcon /></button><button className="icon-button" title="Modifier" onClick={() => setModal({ type: "edit", user })}><EditOutlinedIcon /></button><button className="icon-button danger" title="Supprimer" onClick={() => remove(user)}><DeleteOutlineRoundedIcon /></button></div></td></tr>) : <tr><td colSpan="5"><div className="empty-state">Aucun utilisateur ne correspond à cette recherche.</div></td></tr>}</tbody></table></div>}<div className="pagination"><span>Page {page} sur {pages}</span><div className="pagination-controls"><button disabled={page === 1} onClick={() => setPage(page - 1)}>‹</button><button disabled={page === pages} onClick={() => setPage(page + 1)}>›</button></div></div></section>{modal?.type === "create" && <UserForm onClose={() => setModal(null)} onSaved={saved} />}{modal?.type === "edit" && <UserForm user={modal.user} onClose={() => setModal(null)} onSaved={saved} />}{modal?.type === "view" && <UserDetails user={modal.user} onClose={() => setModal(null)} />}</main></Layout>;
}
export default Users;
